Random Potency First Search
TAPAAL/verifypn pull request #119
Opened 2023-01-03 11:14 UTC by theodor349

Implements a new search heuristic called Random Potency First Search

2023-01-03 18:02 UTC, petergjoel requested changes
We should not have another copy of the tryReach function, these should be merged.
Type-traits or more complex queue classes may do the trick.

But otherwise it is a fine merge. I have a hunch that the queuing can be done more efficient, but that is isolated enough that it is OK to include in the codebase.

Other changes (e.g. options etc.) look fine.

2023-01-03 18:02 UTC, petergjoel commented on src/PetriEngine/Structures/PotencyQueue.cpp
> +                float r = (float) rand() / RAND_MAX;
Why not double?

2023-01-06 09:30 UTC, theodor349 commented on src/PetriEngine/Structures/PotencyQueue.cpp
> +                float r = (float) rand() / RAND_MAX;
Good question, it has now been changed

2023-01-11 10:23 UTC, srba approved these changes

2023-01-11 10:23 UTC, petergjoel approved these changes

2023-01-11 10:23 UTC, merged