Rename POR options switches, purge mixed option
TAPAAL/verifypn pull request #25
Opened 2022-01-04 09:42 UTC by njulrik

Clean-up of naming around POR methods. Our method is now named `automaton` and is set as default, whereas the one based on Liebke's theory is named `liebke`. The help message reflects this. The mixed option which would apply the classic method in non-reachability state has been purged as the notion of 'reachability state' is obsolete.

2022-01-04 10:31 UTC, petergjoel requested changes
Remember to update MCC competition script also (if needed).

2022-01-04 10:31 UTC, petergjoel commented on include/PetriEngine/options.h
> +    //VisibleAutomaton,
If it is commented out, remove it.

2022-01-04 10:31 UTC, petergjoel commented on src/PetriEngine/options.cpp
> +        "                                       - automaton  apply Büchi-guided stubborn set method.\n"
Add paper ref like the others.

2022-01-06 22:46 UTC, srba requested changes
also the tapaal.sh competition script in the MCC22 directory should be updated with the new switches

2022-01-11 10:35 UTC, njulrik commented
I updated the flag on #24, this should be good to go now.

2022-01-11 17:00 UTC, srba commented on src/PetriEngine/options.cpp
> +            } else if (std::strcmp(argv[i + 1], "mix") == 0) {
@njulrik, why do you compare here against "mix", it is not mentioned in the options anymore?

2022-01-15 12:54 UTC, petergjoel commented
Abandoned, changes merged on top of #24

2022-01-15 12:54 UTC, closed without merging